name: typst-slack-bot
services:
    bot:
        # This service is built using the Dockerfile in the current directory.
        build: .
        # This service is always restarted if it ever shuts down (unless stopped manually).
        restart: always
        environment:
            SLACK_BOT_TOKEN_FILE: /run/secrets/slack_bot_token
            SLACK_SIGNING_SECRET_FILE: /run/secrets/slack_signing_secret
            BIND_ADDR: 0.0.0.0:3000
        ports:
            - 3000:3000
        secrets:
            - slack_bot_token
            - slack_signing_secret
        # The `/bot/sqlite` and `/bot/cache` directories are mapped to volumes.
        volumes:
            - sqlite:/bot/sqlite
            - cache:/bot/cache

# SQLite database for tags and package cache are stored in named volumes managed by Docker. As long
# as the volumes are kept in between container rebuilds, they won't need to be recreated.
volumes:
    sqlite:
    cache:

secrets:
    slack_bot_token:
        file: slack_bot_token.txt
    slack_signing_secret:
        file: slack_signing_secret.txt
